services:
  baboon.tools_service:
    class: Baboon\PanelBundle\Service\ToolsService
    arguments:
      - "@kernel"

  baboon.panel.enable_theme_service:
    class: Baboon\PanelBundle\Service\EnableThemeService
    arguments:
      - "@kernel"
      - "@baboon.tools_service"

  baboon.panel.theme_configuration_service:
    class: Baboon\PanelBundle\Service\ThemeConfigurationService
    arguments:
      - "@kernel"

  baboon.panel.theme_deploy:
    class: Baboon\PanelBundle\Service\DeployThemeService
    arguments:
      - "@baboon.panel.theme_configuration_service"
      - "@baboon.panel.enable_theme_service"
