services:
  mustache:
    class: Mustache_Engine

  baboon.tools_service:
    class: Baboon\PanelBundle\Service\ToolsService
    arguments:
      - "@kernel"

  baboon.panel.enable_theme_service:
    class: Baboon\PanelBundle\Service\EnableThemeService
    arguments:
      - "@baboon.tools_service"
      - "@baboon.panel.validate_configuration"

  baboon.panel.theme_configuration_service:
    class: Baboon\PanelBundle\Service\ThemeConfigurationService
    arguments:
      - "@baboon.tools_service"

  baboon.panel.theme_deploy:
    class: Baboon\PanelBundle\Service\DeployThemeService
    arguments:
      - "@baboon.panel.theme_configuration_service"
      - "@baboon.tools_service"
      - "@mustache"

  baboon.panel.ftp_deploy:
    class: Baboon\PanelBundle\Service\FTPDeployService
    arguments:
      - "@baboon.tools_service"
      - "@baboon.panel.theme_deploy"
      - "@doctrine.orm.entity_manager"

  baboon.panel.git_deploy:
    class: Baboon\PanelBundle\Service\GitDeployService
    arguments:
      - "@baboon.tools_service"
      - "@baboon.panel.theme_deploy"
      - "@doctrine.orm.entity_manager"

  baboon.panel.validate_configuration:
    class: Baboon\PanelBundle\Service\ValidateConfigurationService
    arguments:
      - "@baboon.tools_service"

  baboon.panel.dynamic_form:
    class: Baboon\PanelBundle\Service\DynamicFormService
    arguments:
      - "@baboon.tools_service"
      - "@request_stack"
      - "@form.factory"
