services:
  baboon.panel.enable_theme_service:
    class: Baboon\PanelBundle\Service\EnableThemeService
    arguments:
      - "@kernel"

  baboon.panel.theme_configuration_service:
    class: Baboon\PanelBundle\Service\ThemeConfigurationService
    arguments:
      - "@kernel"
