fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@BaboonAppBundle/Controller/"
    type:     annotation

dashboard:
    resource: "@BaboonPanelBundle/Controller/"
    type:     annotation
