fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

bb_panel:
    prefix:   "/dashboard"
    resource: "@BaboonPanelBundle/Resources/config/routing.yml"

app_main:
    path    : /
    defaults: { _controller: "BaboonAppBundle:Default:index" }
    condition: 'not (context.getPathInfo() matches "/_site/")'

app:
    path:     /{path}
    defaults: { _controller: "BaboonAppBundle:Default:index" }
    condition: 'not (context.getPathInfo() matches "/_site/")'
    requirements:
        path: .+