bb_panel_configuration:
    path:     /
    defaults: { _controller: BaboonPanelBundle:Configuration:configuration }

bb_panel_field_configure:
    path:     /configure
    defaults: { _controller: BaboonPanelBundle:Configuration:configure }
    options:
        expose: true