bb_panel_configuration:
    path:     /
    defaults: { _controller: BaboonPanelBundle:Configuration:configuration }

bb_panel_field_configure:
    path:     /configure
    defaults: { _controller: BaboonPanelBundle:Configuration:configure }
    options:
        expose: true

bb_panel_field_save_asset_value:
    path:     /configure/save/asset/value
    defaults: { _controller: BaboonPanelBundle:Configuration:saveAssetValue }
    options:
        expose: true

bb_panel_get_asset_wrap:
    path:     /configure/get/asset/{assetKey}/wrap
    defaults: { _controller: BaboonPanelBundle:Configuration:getAssetWrap }
    options:
        expose: true

bb_panel_add_new_item:
    path:     /configure/add/new/item
    defaults: { _controller: BaboonPanelBundle:Configuration:addNewItem }
    options:
        expose: true
