bb_panel_sync_theme:
    path:     /deploy/sync/theme
    defaults: { _controller: BaboonPanelBundle:Deploy:sync }
    options:
        expose: true

ftp_deploy:
    resource: 'deploy/ftp.yml'

git_deploy:
    resource: 'deploy/git.yml'
